init commit
giantswarm/serviceresource pull request #1
Opened 2018-07-13 12:40 UTC by calvix

initial commit of separating service resources from operators

2018-07-13 13:57 UTC, xh3b4sd requested changes
This PR is too big and does too many things at once. Ideally we would deal with these separate PRs. 

- Circle setup. 
- Resource structure without functionality. 
- Functionality of GetCurrentState. 
- Functionality of GetDesiredState.
- ....

2018-07-13 13:57 UTC, xh3b4sd commented on README.md
> + Package serviceresource implements primitives for service used within Giant Swarm Kubernetes clusters.
The readme badge is missing.

2018-07-13 13:57 UTC, xh3b4sd commented on current.go
> +	clusterID, err := clusterID(obj)
This has to be configurable so the provider operators can set their own key functions.

2018-07-13 13:57 UTC, xh3b4sd commented on current.go
> +	}
This has to be configurable so the provider operators can set their own key functions.

2018-07-13 13:57 UTC, xh3b4sd commented on current.go
> +	if isKVM(obj) {
This is an abstracted resource. Rule of thumb is, grep for the provider in this repo and when you find any result something is wrong. The abstraction we need here apparently is to have configurable hooks.

2018-07-13 13:57 UTC, xh3b4sd commented on desired.go
> +	return r.desiredServicesFunc(ctx, obj)
Please lets keep the calls explicit for our error masking. The masking tells a story via its stack. This story has to match the real call graph and your mental model. This here breaks it.

2018-07-13 13:57 UTC, xh3b4sd commented on resource.go
> +	Name = "servicev14"
This should probably just be `serviceresource`.

2018-07-13 13:57 UTC, xh3b4sd commented on resource.go
> +func DefaultConfig() Config {
We do not maintain these anymore.

2018-07-13 13:57 UTC, xh3b4sd commented on resource.go
> +	desiredServicesFunc func(ctx context.Context, obj interface{}) (*[]apiv1.Service, error)
This is a dependency because it implements behaviour.

2018-07-16 09:32 UTC, calvix commented
I don't understand half of the comments, I don't think its still a good idea that I should continue here.

2018-07-16 14:28 UTC, calvix commented
closing for now, but not deleting - https://github.com/giantswarm/giantswarm/issues/3748

2018-07-16 14:28 UTC, closed without merging